on: [push, repository_dispatch]

jobs:
  bundle-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Add Gemfile
        run: |
          cat > Gemfile << EOM
          source "https://rubygems.pkg.github.com/jcansdale-test" do
            gem "rubygems-publish", "~> 1.1.6", require: "rubygems-publish"
          end
          EOM
      - name: Add main.rb
        run: |
          cat > main.rb << EOM
          require 'rubygems-publish'
          RubyGemsPublish.hello
          EOM
      - name: Authenticate using Bundler
        run: bundle config https://rubygems.pkg.github.com/jcansdale-test token:${{ github.token }}

      - name: Install using Bundler
        run: bundle install

      - name: Run using bundle exec
        run: bundle exec ruby main.rb
